In [1]:
from __future__ import print_function
import torch as t

In [5]:
a = t.Tensor(2,3)
b = t.Tensor([[1,2,3],[4,5,6]])
print (a)
print (b)

tensor([[ 3.0829e-44,  5.1568e-43,  1.4175e-15],
        [-1.2331e-42,  0.0000e+00,  0.0000e+00]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
b.numel()
b_size = b.size()
print (b_size)

torch.Size([2, 3])


In [15]:
c = t.Tensor(b_size)
d = t.Tensor((2,3))
print(c)
print(d)

tensor([[2.1375e+20, 2.5934e-09, 3.4152e-06],
        [4.1961e-08, 1.0486e+21, 1.0753e-05]])
tensor([2., 3.])


In [16]:
t.linspace(1,10,3)

tensor([ 1.0000,  5.5000, 10.0000])

In [17]:
t.randperm(5)

tensor([3, 2, 4, 1, 0])

In [18]:
a = t.arange(0,6)
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [25]:
b = a.view(-1,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [37]:
b.unsqueeze(1)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [38]:
b.unsqueeze(-2)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [39]:
c = b.view(1,1,1,2,3)
c

tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]])

In [40]:
c.squeeze()

tensor([[0, 1, 2],
        [3, 4, 5]])

In [42]:
a[1] = 100
print (a)
print (b)
print (c)

tensor([  0, 100,   2,   3,   4,   5])
tensor([[  0, 100,   2],
        [  3,   4,   5]])
tensor([[[[[  0, 100,   2],
           [  3,   4,   5]]]]])


In [44]:
a = t.randn(3,4)
a

tensor([[-1.1151,  1.4064,  0.8228, -0.0464],
        [-0.7288, -0.2335,  0.0410,  0.7544],
        [-1.4571, -0.2988, -0.6936, -1.3656]])

In [45]:
a>1

tensor([[0, 1, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [46]:
a[a>1]

tensor([1.4064])

In [47]:
a = t.arange(0,16).view(4,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [53]:
index = t.LongTensor([[0,1,2,3]])
a.gather(0,index)
# dim=0，所以竖着看
# 第一竖列的第0个，第二竖列的第1个以此类推

tensor([[ 0,  5, 10, 15]])

In [55]:
index = t.LongTensor([[0,1,2,3],[3,2,1,0]])
b = a.gather(0,index)
b

tensor([[ 0,  5, 10, 15],
        [12,  9,  6,  3]])

In [56]:
index = t.LongTensor([[0,1,2,3],[3,2,1,0]]).t()
b = a.gather(1,index)
b

tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])

In [57]:
x = t.arange(0,27).view(3,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [58]:
x[[1,2],[1,2],[2,0]]
# x[1,1,2],x[2,2,0] 

tensor([14, 24])

In [59]:
x[[0,2],[0],[1]]
# x[0,0,1],x[2,0,1]

tensor([ 1, 19])

In [60]:
a = t.arange(0,6).view(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [61]:
t.clamp(a,min=3)

tensor([[3, 3, 3],
        [3, 4, 5]])

In [62]:
t.clamp(a,max=3)

tensor([[0, 1, 2],
        [3, 3, 3]])

In [63]:
b = t.ones(2,3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [64]:
b.sum(dim = 0, keepdim=True)

tensor([[2., 2., 2.]])

In [65]:
b.sum(dim = 0, keepdim=False)

tensor([2., 2., 2.])

In [66]:
b.sum(dim = 1, keepdim=True)

tensor([[3.],
        [3.]])

In [67]:
b.sum(dim = 1, keepdim=False)

tensor([3., 3.])

In [68]:
a = t.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [69]:
b = t.zeros(2,3,1)
b

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])

In [70]:
a+b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [73]:
a.unsqueeze(0).expand(2,3,2)
# unsqueeze是相当于从没有加了一维，原来的个数其实没有改变
# expand是在已有的基础上加了一维，个数有所增加，复制

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [74]:
import numpy as np

In [75]:
id(a.storage())

1581697715976

In [76]:
a.storage()

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.FloatStorage of size 6]

In [77]:
a.data_ptr()

1581680820928